# Generated by Django 5.2.11 on 2026-02-10 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroceryList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-archived", "position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_slug", models.SlugField(max_length=80, unique=True)),
                ("label_fr", models.CharField(max_length=120)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("quantity", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("checked", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "grocery_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lists_app.grocerylist",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="lists_app.section",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "position", "id"],
                "indexes": [
                    models.Index(
                        fields=["grocery_list", "section"],
                        name="lists_app_i_grocery_0c7e98_idx",
                    )
                ],
            },
        ),
    ]
