# Generated by Django 5.2.11 on 2026-02-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists_app", "0002_seed_sections"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="lists_app.section",
                    ),
                ),
            ],
            options={
                "ordering": ["keyword"],
            },
        ),
    ]
