# Generated by Django 5.2.12 on 2026-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists_app", "0005_add_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="grocerylist",
            name="recipe_links",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
